apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: jw-gitops
  owner: jw-gitops
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/jw-gitops/multi-tenancy-gitops-apps.git
